ahoyapi: v2
usage: CLI utilities for FFA Build Server
commands:
  start-local:
    usage: Start FFA Build Server
    cmd: |
      docker build . -t ffa/build-server:latest -f deployment/development/Dockerfile
      docker-compose up -d
  start-production:
    usage: Start FFA Build Server
    cmd: |
      docker build . -t ffa/build-server:latest -f deployment/staging/Dockerfile
      cp /Users/admin/.ffa/ffa_football2018.p12 src/main/resources
      docker-compose up -d

  stop:
    usage: Stop FFA Build Server
    cmd: |
      docker-compose down


